package projecte;

import java.awt.Graphics;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import projecte.Window.FonsPrograma;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author alumne
 */
public class Contrasenya extends javax.swing.JFrame {

    FonsContrasenya fons = new FonsContrasenya();

    public Contrasenya() {
        this.setContentPane(fons);
        initComponents();
        initMyComponents();
    }

    private void initMyComponents() {
        //Borrem el text de la casella del password        
        textPassword.setText("");

        llegirFitxerConfig();
    }

    private void llegirFitxerConfig() {
        BufferedReader configIn = null;
        PrintWriter configOut = null;

        try {
            if (fitxerConfig.exists()) {
                configIn = new BufferedReader(new FileReader(fitxerConfig));
                configIn.readLine();
                passwd = configIn.readLine().strip();
            } else {
                configOut = new PrintWriter(fitxerConfig);
                configOut.println(10000);
                configOut.print("passwd");
                throw new NumberFormatException();
            }

        } catch (NumberFormatException | NullPointerException | IOException ex) {
            JOptionPane.showMessageDialog(this, "Atenció, problema en el fitxer de configuració");
            passwd = "passwd";
            //dades = new Teclat[100];
        } finally {
            try {
                if (configIn != null) {
                    configIn.close();
                }
                if (configOut != null) {
                    configOut.close();
                }
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Atenció, problema en el fitxer de configuració");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        textPassword.setText("jPasswordField1");

        jLabel1.setFont(new java.awt.Font("Uroob", 0, 24)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Contrasenya:");

        jButton1.setText("Entrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(textPassword)
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jButton1)
                .addContainerGap(193, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (textPassword.getText().equals(passwd)) {
            Window v = new Window();
            v.setVisible(true);

            this.dispose();

        } else {
            JOptionPane.showMessageDialog(this, "Contrasenya incorrecta!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contrasenya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contrasenya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contrasenya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contrasenya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contrasenya().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField textPassword;
    // End of variables declaration//GEN-END:variables

    private static String passwd;

    private static final String NOM_FITXER_CONFIG = "config.txt";
    private File fitxerConfig = new File(NOM_FITXER_CONFIG);

    private static final String NOM_FITXER_DADES = "dades2.dat";
    private File fitxerDades = new File(NOM_FITXER_DADES);

    class FonsContrasenya extends JPanel{
        private Image imatge2;
        
        @Override
        public void paint(Graphics g){
            imatge2 = new ImageIcon(getClass().getResource("/imatges/contra.png")).getImage();            
            g.drawImage(imatge2, 0, 0, getWidth(), getHeight(), this);            
            setOpaque(false);            
            super.paint(g);
        }
    }
}
