package projecte;

import java.awt.Graphics;
import java.awt.Image;
import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.PrintWriter;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.TableColumn;
import modeldades.Teclat;

public class Window extends javax.swing.JFrame {

    FonsPrograma fons = new FonsPrograma();
    
    public Window() {
        this.setContentPane(fons);
        initComponents();
        initMyComponents();
    }

    private void llegirFitxer() {
        if (fitxerDades.exists()) {
            ObjectInputStream entrada = null;

            try {
                entrada = new ObjectInputStream(new BufferedInputStream(new FileInputStream(fitxerDades)));

                int i;

                for (i = 0; i < dades.length; i += 2) {
                    dades[i] = (Teclat) entrada.readObject();
                }

                if (i == dades.length) {
                    entrada.readObject();
                    JOptionPane.showMessageDialog(this, "Atenció, parla amb el programador per a que assigni més espais!");
                    System.exit(1);
                }

            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "Atenció possible pèrdua de dades!");
            } catch (IOException ex) {
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "Atenció possible pèrdua de dades!");
            } finally {
                if (entrada != null) try {
                    entrada.close();
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(this, "Atenció possible pèrdua de dades!");
                }
            }
        }
    }

    private void initMyComponents() {
        llegirFitxerConfig();

        llegirFitxer();

        refrescarDades();
    }

    private void llegirFitxerConfig() {
            BufferedReader configIn = null;
            PrintWriter configOut = null;
            
        try {            
            if (fitxerConfig.exists()) {
                configIn = new BufferedReader(new FileReader(fitxerConfig));
                dades = new Teclat[Integer.parseInt(configIn.readLine().strip())];
            } else {
                configOut = new PrintWriter(fitxerConfig);
                configOut.println(10000);
                configOut.print("passwd");
                throw new NumberFormatException();
            }

        } catch (NumberFormatException | IOException ex) {
            JOptionPane.showMessageDialog(this, "Atenció, problema en el fitxer de configuració");
            dades = new Teclat[100];
        } finally {
            try{
                if(configIn != null) configIn.close();
                if(configOut != null) configOut.close();
            }catch (IOException ex){
                JOptionPane.showMessageDialog(this, "Atenció, problema en el fitxer de configuració");
            }
        }
    }

    private void refrescarDades() {
        tc = taula.loadTableFromArray(dades, Teclat.class, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        numTecles = new javax.swing.JTextField();
        textLlenguatje = new javax.swing.JTextField();
        textMarca = new javax.swing.JTextField();
        preu = new javax.swing.JTextField();
        modelText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        inal = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        ilumin = new javax.swing.JCheckBox();
        borrar = new javax.swing.JButton();
        Insertar = new javax.swing.JButton();
        botoModificar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taula = new beans.JTableMVCGUI();

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(247, 247, 247));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(247, 247, 247));
        jLabel1.setFont(new java.awt.Font("Uroob", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(215, 0, 0));
        jLabel1.setText("TECLATS DANI");

        numTecles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numTeclesActionPerformed(evt);
            }
        });

        textLlenguatje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textLlenguatjeActionPerformed(evt);
            }
        });

        textMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMarcaActionPerformed(evt);
            }
        });

        preu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preuActionPerformed(evt);
            }
        });

        modelText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelTextActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Uroob", 0, 24)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Marca");

        jLabel3.setFont(new java.awt.Font("Uroob", 0, 24)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Model");

        jLabel4.setFont(new java.awt.Font("Uroob", 0, 24)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Llenguatje");

        jLabel5.setBackground(new java.awt.Color(247, 247, 247));
        jLabel5.setFont(new java.awt.Font("Uroob", 0, 24)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Num. Tecles");

        jLabel6.setFont(new java.awt.Font("Uroob", 0, 24)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Preu");

        jLabel7.setFont(new java.awt.Font("Uroob", 0, 24)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("Il·luminació");

        inal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inalActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Uroob", 0, 24)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("Inalàmbric");

        ilumin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iluminActionPerformed(evt);
            }
        });

        borrar.setText("BORRAR");
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });

        Insertar.setText("INSERTAR");
        Insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarActionPerformed(evt);
            }
        });

        botoModificar.setText("MODIFICAR");
        botoModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoModificarActionPerformed(evt);
            }
        });

        taula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        taula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                taulaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(taula);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(18, 18, 18)
                                            .addComponent(textMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(18, 18, 18)
                                            .addComponent(modelText, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(textLlenguatje, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(86, 86, 86)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(244, 244, 244)
                                .addComponent(Insertar)
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(numTecles, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(botoModificar)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(18, 18, 18)
                                            .addComponent(preu, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(inal))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ilumin))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(borrar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 894, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ilumin)
                                .addComponent(jLabel7))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(numTecles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(preu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(inal, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modelText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textLlenguatje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Insertar)
                    .addComponent(botoModificar)
                    .addComponent(borrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void numTeclesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numTeclesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numTeclesActionPerformed

    private void textLlenguatjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textLlenguatjeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textLlenguatjeActionPerformed

    private void textMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMarcaActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void preuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_preuActionPerformed

    private void modelTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelTextActionPerformed

    private void inalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inalActionPerformed

    private void iluminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iluminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iluminActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        int filaSel = taula.getSelectedRow();

        if (filaSel != -1) {
            taula.getColumnModel().addColumn(tc);
            Teclat borrar = (Teclat)taula.getModel().getValueAt(filaSel,taula.getColumnCount() - 1);
            taula.getColumnModel().removeColumn(tc);
            int i;
            for (i = 0; i < dades.length && (dades[i] == null || !dades[i].equals(borrar)); i++);
            if (i < dades.length) {
                dades[i] = null;
                refrescarDades();
            } else {
                JOptionPane.showMessageDialog(this, "Parla amb el programador...");
            }
            refrescarDades();
            JOptionPane.showMessageDialog(this, "Teclat\n"+borrar+"\nesborrat correctament!");
        } else {
            JOptionPane.showMessageDialog(this, "Per borrar has de seleccionar un teclat de la taula!");
        }
    }//GEN-LAST:event_borrarActionPerformed

    private void InsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarActionPerformed
        try {
            Teclat nou = new Teclat();

            nou.setMarca(textMarca.getText().strip());
            nou.setModel(modelText.getText().strip());
            nou.setLlenguatje(textLlenguatje.getText().strip());
            nou.setNum_tecles(Integer.parseInt(numTecles.getText().strip()));
            nou.setPreu(Double.parseDouble(preu.getText().strip()));
            nou.setIlluminacio(ilumin.isSelected());
            nou.setInalambric(inal.isSelected());

            if (nou.getNum_tecles() < 0) {
                throw new java.lang.NullPointerException();
            }
            if (nou.getPreu() < 0) {
                throw new java.lang.NullPointerException();
            }

            int i;
            for (i = 0; i < dades.length && dades[i] != null; i++);

            if (i < dades.length) {
                dades[i] = nou;
                refrescarDades();
            } else {
                JOptionPane.showMessageDialog(this, "Ho sento però no caben més teclats");
            }

        } catch (java.lang.NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "El preu/número de tecles no pot ser negatiu!");
        } catch (java.lang.NullPointerException ex) {
            JOptionPane.showMessageDialog(this, "El preu/número de tecles no pot ser negatiu!");
        }
    }//GEN-LAST:event_InsertarActionPerformed

    private void botoModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoModificarActionPerformed
        int filaSel = taula.getSelectedRow();

        if (filaSel != -1) {
            taula.getColumnModel().addColumn(tc);
            Teclat modificar = (Teclat) taula.getModel().getValueAt(filaSel, taula.getColumnCount() - 1);
            taula.getColumnModel().removeColumn(tc);

            modificar.setMarca(textMarca.getText().strip());
            modificar.setModel(modelText.getText().strip());
            modificar.setLlenguatje(textLlenguatje.getText().strip());
            modificar.setNum_tecles((int) Double.parseDouble(numTecles.getText().strip()));
            modificar.setPreu(Double.parseDouble(preu.getText().strip()));
            modificar.setIlluminacio(ilumin.isSelected());
            modificar.setInalambric(inal.isSelected());

            refrescarDades();
            JOptionPane.showMessageDialog(this, "Teclat\n"+modificar+"\nmodificada correctament!");
        } else {
            JOptionPane.showMessageDialog(this, "Per modificar has de seleccionar un teclat de la taula!");
        }
    }//GEN-LAST:event_botoModificarActionPerformed

    private void taulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taulaMouseClicked
        int filaSel = taula.getSelectedRow();

        if (filaSel != -1) {
            textMarca.setText(taula.getModel().getValueAt(filaSel, 3).toString());
            modelText.setText(taula.getModel().getValueAt(filaSel, 4).toString());
            textLlenguatje.setText(taula.getModel().getValueAt(filaSel, 2).toString());
            numTecles.setText(taula.getModel().getValueAt(filaSel, 5).toString());
            preu.setText(taula.getModel().getValueAt(filaSel, 6).toString());
            ilumin.setSelected((boolean) taula.getModel().getValueAt(filaSel, 0));
            inal.setSelected((boolean) taula.getModel().getValueAt(filaSel, 1));
        }
    }//GEN-LAST:event_taulaMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        ObjectOutputStream sortida = null;
        try {
            //Guardem els teclats del vector al fitxer
            sortida = new ObjectOutputStream(new BufferedOutputStream(new FileOutputStream(fitxerDades)));

            for (int i = 0; i < dades.length; i++) {
                if (dades[i] != null) {
                    sortida.writeObject(dades[i]);
                }
            }

        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Atenció possible pèrdua de dades!");
        } catch (IOException ex) {
            //No cal fer res, ja que aqui entrarem quan ja sabem que el fitxer existeix i per tant aquest error no succeirà mai.
        } finally {
            try {
                if (sortida != null) {
                    sortida.close();
                }
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Atenció possible pèrdua de dades!");
            }
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Insertar;
    private javax.swing.JButton borrar;
    private javax.swing.JButton botoModificar;
    private javax.swing.JCheckBox ilumin;
    private javax.swing.JCheckBox inal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField modelText;
    private javax.swing.JTextField numTecles;
    private javax.swing.JTextField preu;
    private beans.JTableMVCGUI taula;
    private javax.swing.JTextField textLlenguatje;
    private javax.swing.JTextField textMarca;
    // End of variables declaration//GEN-END:variables

    //My properties
    private Teclat[] dades = null;
    private TableColumn tc;

    //Propietats per al tractament de fitxers
    static final String NOM_FITXER_DADES = "dades2.dat";
    static File fitxerDades = new File(NOM_FITXER_DADES);

    static final String NOM_FITXER_CONFIG = "config.txt";
    static File fitxerConfig = new File(NOM_FITXER_CONFIG);
    
    class FonsPrograma extends JPanel{
        private Image imatge;
        
        @Override
        public void paint(Graphics g){
            imatge = new ImageIcon(getClass().getResource("/imatges/teclat.png")).getImage();            
            g.drawImage(imatge, 0, 0, getWidth(), getHeight(), this);            
            setOpaque(false);            
            super.paint(g);
        }
    }
}
